version: '3'
services:
# Postgres server
  sample_database:
    container_name: postgres-execq
    image: postgres-execq:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
