version: '3'
services:
# Postgres server
  sample_database:
    container_name: postgres-mecab
    image: postgres-mecab:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
