version: '3'
services:
# Postgres server
  postgres-mecab:
    build: .
    container_name: postgres-mecab
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./mecabrc:/etc/mecabrc
    ports:
      - "5432:5432"
