version: '3'
services:
# Postgres server
  postgres-mecab:
    build: .
    container_name: postgres-mecab
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./:/work
      - ./mecabrc:/etc/mecabrc
    command: >
      tail -F /dev/null
    ports:
    - "5432:5432"
