version: '3'
services:
# Postgres server
  postgres-mecab :
    build: .
    container_name: postgres-mecab
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
